### ISSUE TITLE
When I call  collectView.reloadSections(NSIndexSet(index: 2)),the SBCollectionViewReusableView covered my cell

### ISSUE THREAD

**Issue by cailianfeng** [c0ming/SBCollectionViewFlowLayout#3]
collectView.reloadSections(NSIndexSet(index: 2)) 
I can't upload a Screenshot

**Comment by c0ming** [comment]
fixed in 修复两个刷新时遇到的bug #4

**Comment by clf1268** [comment]
遮盖cell的问题并没有解决，滑动页面依然会有的cell被遮盖住，

**Comment by c0ming** [comment]
@clf1268 可否提供详细的系统信息和怎么使用时出现这样问题的？

**Comment by clf1268** [comment]
10.3.1,点击某个按钮，刷新页面的一部分collectView.reloadSections(<#T##sections: NSIndexSet##NSIndexSet#>)，然后上下滑动页面，多滑动几次section会依次被覆盖住。每次覆盖一个section
